require: rubocop-rails

AllCops:
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Max: 14

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 100

Metrics/ModuleLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 100

Layout/LineLength:
  Max: 120

Naming/MethodName:
  EnforcedStyle: snake_case

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/DoubleNegation:
  Enabled: false
